[package]
edition.workspace = true
name = "order_book"
version.workspace = true

[dependencies]
chrono = "0.4.40"
dashmap = "6.1.0"
getrandom = "0.3.2"
ordered-float = "5.0.0"
parking_lot = "0.12.3"
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["v7"] }
